In [40]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split,RandomizedSearchCV,GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv("train_ctrUa4K.csv")
train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [4]:
train.drop("Loan_ID",inplace=True,axis=1)

In [5]:
train['Gender'].replace({np.nan:'Male'},inplace=True)
train["Gender"].replace({'Male':1,'Female':0},inplace=True)
train['Married'].replace({np.nan:'Yes'},inplace=True)
train["Married"].replace({'Yes':1,'No':0},inplace=True)
train['Dependents'].replace({np.nan:'0'},inplace=True)
train['Dependents'].replace({'3+':'3'},inplace=True)
train['Education'].replace({"Graduate":1,"Not Graduate":0},inplace=True)
train['LoanAmount'].replace({"np.nan":train['LoanAmount'].median()},inplace=True)
train['Loan_Amount_Term'].replace({"np.nan":train['Loan_Amount_Term'].mean()},inplace=True)
train['Credit_History'].replace({"np.nan":train['Credit_History'].median()},inplace=True)
train['Property_Area'].replace({'Urban':2, 'Rural':0, 'Semiurban':1},inplace=True)

In [6]:
train["Self_Employed"].replace({'Yes':1,'No':0},inplace=True)
train["Dependents"]=train["Dependents"].astype(float)
train["Self_Employed"].replace({np.nan:'0'},inplace=True)
train['LoanAmount'].replace({np.nan:'128'},inplace=True)
train['Loan_Amount_Term'].replace({np.nan:"360"},inplace=True)
train["Self_Employed"]=train["Self_Employed"].astype(float)
train['Loan_Amount_Term']=train['Loan_Amount_Term'].astype(float)
train['LoanAmount']=train['LoanAmount'].astype(float)
train['Credit_History'].replace({np.nan:1},inplace=True)

In [7]:
train["Loan_Status"].replace({'Y':1,'N':0},inplace=True)

In [8]:
y =train["Loan_Status"]
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

In [9]:
train.drop("Loan_Status",inplace=True,axis=1)

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             614 non-null    int64  
 1   Married            614 non-null    int64  
 2   Dependents         614 non-null    float64
 3   Education          614 non-null    int64  
 4   Self_Employed      614 non-null    float64
 5   ApplicantIncome    614 non-null    int64  
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    float64
 10  Property_Area      614 non-null    int64  
dtypes: float64(6), int64(5)
memory usage: 52.9 KB


In [11]:
std_scaled = StandardScaler()
x=std_scaled.fit_transform(train)

In [12]:
x =pd.DataFrame(x)

# Train Test Split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=10,test_size=0.2,stratify=y)

# Model Training

In [14]:
Random_model = RandomForestClassifier()
Random_model.fit(x_train,y_train)

RandomForestClassifier()

In [15]:
# Training Data accuracy
y_pred_train =Random_model.predict(x_train)

cnf_matrix = confusion_matrix(y_train,y_pred_train)
print(f"confusion matrix = \n{cnf_matrix}")

acc_score = accuracy_score(y_train,y_pred_train)
print(f" accuracy score = \n {acc_score}")

cls_report =classification_report(y_train,y_pred_train)
print(f"classification report = \n{cls_report}")

confusion matrix = 
[[154   0]
 [  0 337]]
 accuracy score = 
 1.0
classification report = 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       154
           1       1.00      1.00      1.00       337

    accuracy                           1.00       491
   macro avg       1.00      1.00      1.00       491
weighted avg       1.00      1.00      1.00       491



In [16]:
##Testing Data accuracy
y_pred = Random_model.predict(x_test)

cnf_matrix = confusion_matrix(y_test,y_pred)
print(f" Confusion matrix = \n{cnf_matrix}")

acc_score = accuracy_score(y_test,y_pred)
print(f" accuracy score = \n{acc_score}")

clf_report = classification_report(y_test,y_pred)
print(f"classiication Report = \n{clf_report}")

 Confusion matrix = 
[[16 22]
 [ 3 82]]
 accuracy score = 
0.7967479674796748
classiication Report = 
              precision    recall  f1-score   support

           0       0.84      0.42      0.56        38
           1       0.79      0.96      0.87        85

    accuracy                           0.80       123
   macro avg       0.82      0.69      0.71       123
weighted avg       0.81      0.80      0.77       123



# Hyperparameter Tunning

In [42]:
rf_model = RandomForestClassifier()
# bootstrap=True,
# oob_score=False,

hyp_grid = {
    'n_estimators':np.arange(10,200,10),
    'criterion':['gini','entropy'],
    'max_depth':np.arange(2,10),
    'min_samples_split':np.arange(2,20),
    'min_samples_leaf':np.arange(2,15),
    
}

rscv_rf_model = RandomizedSearchCV(rf_model,hyp_grid,cv=5)
rscv_rf_model.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': array([2, 3, 4, 5, 6, 7, 8, 9]),
                                        'min_samples_leaf': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
                                        'min_samples_split': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19]),
                                        'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])})

In [43]:
rscv_rf_model.best_estimator_

RandomForestClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=18,
                       n_estimators=120)

In [44]:
rf_model = RandomForestClassifier(criterion='gini', 
                                  max_depth=5, 
                                  min_samples_leaf=5,
                                  min_samples_split=18, 
                                  n_estimators=120,
                                  max_features='auto',
                                  oob_score=True,
                                  bootstrap=True
)

In [46]:
rf_model.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=18,
                       n_estimators=120, oob_score=True)

# Training Data Accuracy

In [47]:
# Train data Accuracy 
y_pred_train = rf_model.predict(x_train)

cnf_matrix = confusion_matrix(y_train,y_pred_train)
print(f"Confusion Matrix = \n{cnf_matrix}")

acc_score = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = \n{acc_score}")

clf_report = classification_report(y_train,y_pred_train)
print(f"Classification Report = \n{clf_report}")

Confusion Matrix = 
[[ 67  87]
 [  6 331]]
Accuracy Score = 
0.8105906313645621
Classification Report = 
              precision    recall  f1-score   support

           0       0.92      0.44      0.59       154
           1       0.79      0.98      0.88       337

    accuracy                           0.81       491
   macro avg       0.85      0.71      0.73       491
weighted avg       0.83      0.81      0.79       491



In [48]:
# Test Data Accuracy
y_pred = rf_model.predict(x_test)

cnf_matrix = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix = \n{cnf_matrix}")

acc_score = accuracy_score(y_test,y_pred)
print(f"Accuracy Score = \n{acc_score}")

clf_report = classification_report(y_test,y_pred)
print(f"Classification Report = \n{clf_report}")

Confusion Matrix = 
[[16 22]
 [ 1 84]]
Accuracy Score = 
0.8130081300813008
Classification Report = 
              precision    recall  f1-score   support

           0       0.94      0.42      0.58        38
           1       0.79      0.99      0.88        85

    accuracy                           0.81       123
   macro avg       0.87      0.70      0.73       123
weighted avg       0.84      0.81      0.79       123



In [51]:
y_test[:5]

507    0
493    1
434    1
125    1
294    1
Name: Loan_Status, dtype: int64

In [52]:
y_pred[:5]

array([1, 1, 1, 1, 1], dtype=int64)

# Test Data

In [19]:
test = pd.read_csv("test_lAUu6dG.csv")

In [20]:
test.head(5)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [21]:
test.drop("Loan_ID",inplace=True,axis=1)

In [22]:

test['Gender'].replace({np.nan:'Male'},inplace=True)
test["Gender"].replace({'Male':1,'Female':0},inplace=True)
test['Married'].replace({np.nan:'Yes'},inplace=True)
test["Married"].replace({'Yes':1,'No':0},inplace=True)
test['Dependents'].replace({np.nan:'0'},inplace=True)
test['Dependents'].replace({'3+':'3'},inplace=True)
test['Education'].replace({"Graduate":1,"Not Graduate":0},inplace=True)
test['Property_Area'].replace({'Urban':2, 'Rural':0, 'Semiurban':1},inplace=True)
test["Self_Employed"].replace({'Yes':1,'No':0},inplace=True)
test["Dependents"]=test["Dependents"].astype(float)
test["Self_Employed"].replace({np.nan:'0'},inplace=True)
test['LoanAmount'].replace({np.nan:'128'},inplace=True)
test['Loan_Amount_Term'].replace({np.nan:"360"},inplace=True)
test["Self_Employed"]=test["Self_Employed"].astype(float)
test['Loan_Amount_Term']=test['Loan_Amount_Term'].astype(float)
test['LoanAmount']=test['LoanAmount'].astype(float)
test['Credit_History'].replace({np.nan:1},inplace=True)

In [23]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             367 non-null    int64  
 1   Married            367 non-null    int64  
 2   Dependents         367 non-null    float64
 3   Education          367 non-null    int64  
 4   Self_Employed      367 non-null    float64
 5   ApplicantIncome    367 non-null    int64  
 6   CoapplicantIncome  367 non-null    int64  
 7   LoanAmount         367 non-null    float64
 8   Loan_Amount_Term   367 non-null    float64
 9   Credit_History     367 non-null    float64
 10  Property_Area      367 non-null    int64  
dtypes: float64(5), int64(6)
memory usage: 31.7 KB


In [53]:
y_pred = rf_model.predict(test)

C:\Users\prati\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [54]:
y_pred[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [55]:
y_pred =pd.Series(y_pred)

In [56]:
y_pred.replace({1:'Yes',0:'No'},inplace=True)

In [57]:
type(y_pred)

pandas.core.series.Series

In [58]:
test1 = pd.read_csv("test_lAUu6dG.csv")

In [59]:
df =test1["Loan_ID"]

In [60]:
type(df)

pandas.core.series.Series

In [61]:
df1 =pd.concat([df,y_pred],axis=1)

In [62]:
df1.rename(columns={0:"Loan_Status"},inplace=True)

In [63]:
df1.to_csv(r"W:\Data S work file\Data Scienec Project\Loan_prediction_analytics vidya\df_rf.csv")

In [35]:
df1.value_counts()

Loan_ID   Loan_Status
LP001015  Yes            1
LP002389  Yes            1
LP002383  No             1
LP002376  No             1
LP002375  Yes            1
                        ..
LP001627  Yes            1
LP001622  No             1
LP001613  No             1
LP001611  No             1
LP002989  No             1
Length: 367, dtype: int64

In [37]:
y_pred.value_counts()

No     243
Yes    124
dtype: int64

In [49]:
rf_model.score(x_train,y_train)

0.8105906313645621

In [50]:
rf_model.score(x_test,y_test)

0.8130081300813008